### PR TITLE
Fix README information

### PR DESCRIPTION
**Pull request by GrowlyX**
The previous information was extremely outdated. No one knew about your migration to horse entity.

### CODE REVIEW

**Comment by therealnv6** [comment]
35 seconds ago

**Comment by GrowlyX** [comment]
Wrong: 
image

**Comment by therealnv6** [comment]
image

**Comment by GrowlyX** [comment]
image

**Comment by therealnv6** [comment]
image

**Comment by GrowlyX** [comment]
image

**Comment by therealnv6** [comment]
image

**Comment by GrowlyX** [comment]
image

**Comment by therealnv6** [comment]
image

**Comment by GrowlyX** [comment]
image

**Comment by GrowlyX** [comment]
Iaem sory.

**Comment by therealnv6** [comment]
image

**Comment by GrowlyX** [comment]
image

**Comment by GrowlyX** [comment]
Iaem sorry. X3

**Comment by GrowlyX** [comment]
Iam soerry, meant X@.

**Comment by GrowlyX** [comment]
Iaem sorry, meant X2

**Comment by GrowlyX** [comment]
Iaem sorry, forgot paerod.

**Comment by GrowlyX** [comment]
Iaemsorry, imspelled period.

**Comment by GrowlyX** [comment]
Iaem sorry, for got space.

**Comment by GrowlyX** [comment]
Iaem sorry, added new space accidentl.

**Comment by mxtejj** [comment]
thanks

**Pull request closed without merging**
